name: Update campaign finance data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Python dependencies
      run: pip install sqlite-utils
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install Node dependencies
      run: npm install
    - name: Run scripts
      run: |-
        node scripts/index.js
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add data src/lib/data.json
        git pull origin $GITHUB_REF
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push